### ISSUE TITLE
Fatal error: Cannot redeclare determine_locale()

### ISSUE THREAD

**Issue by szepeviktor** [php-stubs/acf-pro-stubs#17]
https://github.com/php-stubs/acf-pro-stubs/blob/2a16e7503bc18e182beed2cd9a0acc551b1c90c8/generate.sh#L28-L29

test
```
php -r 'require "../wordpress-stubs/wordpress-stubs.php"; require "acf-pro-stubs.php";'
```

**Comment by szepeviktor** [comment]
If I would maintain this repo I would remove all commits from the last 4 hours ...

But it is You!

**Comment by juhojama** [comment]
Sorry for the inconvenience.

> If I would maintain this repo I would remove all commits from the last 4 hours

No problem, will do.

**Comment by szepeviktor** [comment]
That regexp needs to work on lines beginning with spaces.
Now the stubs have `namespace {`
