### ISSUE TITLE
Please update the stubs

### ISSUE THREAD

**Issue by isaumya** [php-stubs/acf-pro-stubs#3]
ACF 5.9.9 has been released. Please update the stubs.

**Comment by szepeviktor** [comment]
Hello @isaumya! I thought no one uses this package :)

**Comment by isaumya** [comment]
Really? I use it on all my projects. Why do you think that?

**Comment by szepeviktor** [comment]
> Why do you think that?

ACF is a one-man-show, static analysis is for quality assurance. These two are opposite of each other.

**Comment by szepeviktor** [comment]
The last change was in https://github.com/php-stubs/acf-pro-stubs/compare/v5.9.6...v5.9.7
The two latest releases brought no changes in stubs.
Please check them if you have time.

Thank you for reporting it!

**Comment by isaumya** [comment]
Hey @szepeviktor,
I am not sure if anything was changed. But I just informed you so that you can just rn the code and check if there was anything updated.

Moreover, I have a request, not sure if you can do it as I think most of your stub generation is kinda automated.

Currently inside your stubs you have just:

```php
function get_row_index()
{
}
```

mentioned. I was wondering if you can add the proper comment above it like this:

```php
/**
*  get_row_index
*
*  This function returns the current row index within a have_rows() loop.
*
*  @type	function
*  @date	2/09/13
*  @since	5.3.4
*
*  @param	void
*  @return	int A numeric index of the current row. See notes regarding index offset.
*/
function get_row_index()
{
}
```

As I have to manually add it each time after I install these stubs. If you can add it would be really helpful.

**Comment by szepeviktor** [comment]
> stub generation is kinda automated

Without "kinda"!

> As I have to manually add it each time after I install these stubs.

Me too!

### Options

1. Add it yourself each time
2. Send a PR each time
3. Develop a shell/PHP/diff/* script that adds it
4. Tell Elliot to add it
5. Don't care
